### ISSUE TITLE
Hi，在webman里使用报错

### ISSUE THREAD

**Issue by jetlong** [shopwwi/laravel-cache#1]
PHP环境：php 8.1
使用的安装命令为：
`composer require shopwwi/laravel-cache`

使用缓存提示如下错误：

`
[2023-03-30 23:19:15] default.ERROR: 127.0.0.1 GET 0.0.0.0:8787/pay/WechatPay/createOrder
Error: Class "Illuminate\Filesystem\Filesystem" not found in /var/php/hello-webman/webman/vendor/shopwwi/laravel-cache/src/CacheFactory.php:225
Stack trace:
#0 /var/php/hello-webman/webman/vendor/shopwwi/laravel-cache/src/CacheFactory.php(119): Shopwwi\LaravelCache\CacheFactory->createFileDriver(Array)
#1 /var/php/hello-webman/webman/vendor/shopwwi/laravel-cache/src/CacheFactory.php(72): Shopwwi\LaravelCache\CacheFactory->resolve('file')
#2 /var/php/hello-webman/webman/vendor/shopwwi/laravel-cache/src/CacheFactory.php(50): Shopwwi\LaravelCache\CacheFactory->getStoreName('file')
#3 /var/php/hello-webman/webman/vendor/shopwwi/laravel-cache/src/CacheFactory.php(341): Shopwwi\LaravelCache\CacheFactory->store()
#4 /var/php/hello-webman/webman/vendor/shopwwi/laravel-cache/src/Cache.php(47): Shopwwi\LaravelCache\CacheFactory->__call('set', Array)
#5 /var/php/hello-webman/webman/app/pay/service/WechatPayService.php(11): Shopwwi\LaravelCache\Cache::__callStatic('set', Array)
#6 /var/php/hello-webman/webman/app/ApiEntryController.php(37): app\pay\service\WechatPayService->createOrder(Array)
#7 /var/php/hello-webman/webman/vendor/workerman/webman-framework/src/App.php(388): app\ApiEntryController->index(Object(support\Request))
#8 /var/php/hello-webman/webman/vendor/workerman/webman-framework/src/App.php(560): Webman\App::Webman\{closure}(Object(support\Request))
#9 /var/php/hello-webman/webman/vendor/workerman/webman-framework/src/App.php(148): Webman\App::findRoute(Object(Workerman\Connection\TcpConnection), '/pay/WechatPay/...', 'GET/pay/WechatP...', Object(support\Request))
#10 /var/php/hello-webman/webman/vendor/workerman/workerman/Connection/TcpConnection.php(646): Webman\App->onMessage(Object(Workerman\Connection\TcpConnection), Object(support\Request))
#11 /var/php/hello-webman/webman/vendor/workerman/workerman/Events/Select.php(311): Workerman\Connection\TcpConnection->baseRead(Resource id #357)
#12 /var/php/hello-webman/webman/vendor/workerman/workerman/Worker.php(1629): Workerman\Events\Select->loop()
#13 /var/php/hello-webman/webman/vendor/workerman/workerman/Worker.php(1423): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#14 /var/php/hello-webman/webman/vendor/workerman/workerman/Worker.php(1397): Workerman\Worker::forkWorkersForLinux()
#15 /var/php/hello-webman/webman/vendor/workerman/workerman/Worker.php(560): Workerman\Worker::forkWorkers()
#16 /var/php/hello-webman/webman/vendor/workerman/webman-framework/src/support/App.php(131): Workerman\Worker::runAll()
#17 /var/php/hello-webman/webman/vendor/webman/console/src/Commands/StartCommand.php(29): support\App::run()
#18 /var/php/hello-webman/webman/vendor/symfony/console/Command/Command.php(312): Webman\Console\Commands\StartCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/php/hello-webman/webman/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/php/hello-webman/webman/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(Webman\Console\Commands\StartCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/php/hello-webman/webman/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/php/hello-webman/webman/webman(45): Symfony\Component\Console\Application->run()
#23 {main} [] []
`

**Comment by phcent** [comment]
composer require Illuminate/Filesystem
