### ISSUE TITLE
webman1.5使用redis时报错

### ISSUE THREAD

**Issue by mxh861001** [shopwwi/laravel-cache#2]
Cache::tags(['people', 'artists'])->put('John', $john, $seconds);
`
Error: Call to undefined function Illuminate\Cache\now() in /Users/dev/Desktop/work/webman/vendor/illuminate/cache/RedisTagSet.php:19
`

**Comment by phcent** [comment]
看看是否是10.0版本造成得 将Illuminate\Cache也升级为对应版本即可
